import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const js=ts.transpileModule(fs.readFileSync('lib/flight/music.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {TakeoffMusic}=await import(`data:text/javascript;base64,${Buffer.from(js).toString('base64')}`);
const sources=[],levels=[];
const context={currentTime:0,destination:{},decodeAudioData:async()=>({duration:120}),createGain:()=>({gain:{value:0,setValueAtTime(){},setTargetAtTime(v){levels.push(v);}},connect(){},disconnect(){}}),createBufferSource:()=>{const source={connect(){},disconnect(){},start(_,offset){this.offset=offset;},stop(){this.stopped=true;},onended:null};sources.push(source);return source;}};
const music=new TakeoffMusic();await music.load({arrayBuffer:async()=>new ArrayBuffer(1)},context);
const s={phase:'Preflight',running:false,paused:false,onGround:true,touchdown:null,warning:''};
music.update(s,false,context);assert.equal(sources.length,0);
s.phase='Takeoff';s.running=true;music.update(s,false,context);assert.equal(sources.length,0);
s.onGround=false;s.phase='Climb';music.update(s,false,context);assert.equal(sources.length,1);assert.equal(sources[0].offset,0);
context.currentTime=8;s.paused=true;music.update(s,false,context);assert.equal(sources[0].stopped,true);
context.currentTime=30;s.paused=false;music.update(s,false,context);assert.equal(sources[1].offset,8);
music.update(s,true,context);assert.equal(levels.at(-1),0);
s.warning='STALL';music.update(s,false,context);assert.equal(levels.at(-1),.075);
s.warning='';s.phase='Complete';s.running=false;music.update(s,false,context);assert.equal(sources[1].stopped,true);
music.reset();s.phase='Takeoff';s.running=true;s.onGround=true;music.update(s,false,context);assert.equal(sources.length,2);
s.onGround=false;music.update(s,false,context);assert.equal(sources[2].offset,0);
sources[2].onended();music.update(s,false,context);assert.equal(sources.length,3,'song must not restart after ending');
music.clear();music.update(s,false,context);assert.equal(sources.length,3);
music.dispose();console.log('Takeoff music checks passed: liftoff, pause/resume offset, mute, warning ducking, flight end, reset, play once, removal.');
