'use client';
import styles from './PilotOverlay.module.css';
import {Footprints,Plane,Sun,Moon,MapPin,Compass,Camera} from 'lucide-react';
import {boardingPoint,canBoard,inLounge,loungePoint,cabinLocal,nearFlightSeat,nearCabinExit,type PilotState} from '@/lib/flight/pilot';
import type {FlightState} from '@/lib/flight/physics';
export function PilotOverlay({p,s,onBoard,onRest,onPause,onView}:{p:PilotState;s:FlightState;onBoard:()=>void;onRest:(night:boolean)=>void;onPause:()=>void;onView:()=>void}){
 const cabin=p.zone==='Cabin',local=cabinLocal(p,s),seat=nearFlightSeat(p,s),exit=nearCabinExit(p,s),door=boardingPoint(s),lounge=loungePoint(p),near=canBoard(p,s),inside=inLounge(p),distance=Math.hypot(p.x-door.x,p.z-door.z);
 const sx=(x:number)=>150+(x-p.x)*.65,sz=(z:number)=>120+(z-p.z)*.65;
 const action=seat?'Sit in captain’s seat':exit?'Leave aircraft':near?'Enter cabin':'';
 return <div className={styles.overlay}>
 <div className={styles.title}><span className="eyebrow"><Footprints size={14}/> PILOT LIFE · {cabin?'ABOARD YOUR 737':p.airport===0?'SEATTLE':'EVERETT'}</span><h1>{cabin?(local.z<-15?'Step into the flight deck.':'Explore your aircraft.'):inside?'A moment between flights.':'Your day beyond the cockpit.'}</h1><p>{p.view} · {cabin?(local.z<-15?'Cockpit':'Passenger cabin'):inside?'Pilot lounge':'On foot'}</p></div>
 <aside className={styles.map+' panel'}><div className="panel-heading"><Compass size={14}/> {cabin?'AIRCRAFT INTERIOR':'AIRPORT & SURROUNDINGS'}</div>
 {cabin?<svg width="300" height="240" style={{width:'100%',height:'auto'}} viewBox="0 0 300 240" aria-label="Cabin plan showing pilot, cockpit and forward exit"><rect width="300" height="240" fill="#18343d"/><rect x="121" y="40" width="58" height="186" rx="19" fill="#49616c"/><text x="190" y="30" fill="#e6c18a" fontSize="11">COCKPIT</text><text x="20" y="63" fill="#e6c18a" fontSize="11">EXIT →</text>{Array.from({length:24},(_,i)=><g key={i} fill="#879caa"><rect x="125" y={77+i*5.5} width="15" height="4"/><rect x="160" y={77+i*5.5} width="15" height="4"/></g>)}<circle cx={150+local.x*15} cy={44+(local.z+16.65)*5.7} r="5" fill="#afffd1"/></svg>:<svg width="300" height="240" style={{width:'100%',height:'auto'}} viewBox="0 0 300 240" aria-label="Local walking map"><rect width="300" height="240" fill="#385b4c"/><rect x={sx(-30)} y={sz(p.airport-1500)} width="39" height="1950" fill="#52636a"/><path d={`M ${sx(50)} ${sz(p.airport+1110)} H ${sx(102)}`} stroke="#a3ac94" strokeWidth="5"/><rect x={sx(78)} y={sz(p.airport+1092)} width="16" height="11" fill="#e9c995"/><text x={sx(90)+12} y={sz(lounge.z)} fill="#fff" fontSize="10">LOUNGE</text><g transform={`translate(${sx(s.x)} ${sz(s.z)}) rotate(${s.heading*180/Math.PI})`}><path d="M 0 -10 L 3 -1 L 10 4 L 2 3 L 2 8 L -2 8 L -2 3 L -10 4 L -3 -1 Z" fill="#f4b264"/></g><circle cx="150" cy="120" r="6" fill="#bcffe0"/><path d="M 0 -16 L -5 -7 L 5 -7 Z" fill="#bcffe0" transform={`translate(150 120) rotate(${p.heading*180/Math.PI})`}/></svg>}
 <div className={styles.distance}><span>{cabin?'Cockpit ↑ · Cabin ↓':`Aircraft ${Math.round(distance)} m`}</span><span>{(p.walked/1000).toFixed(2)} km</span></div></aside>
 {p.view==='First person'&&<div className={styles.crosshair} aria-hidden="true">·</div>}
 <aside className={styles.action+' panel'}><span className="eyebrow"><MapPin size={13}/> {cabin?'ON BOARD':near?'YOUR BOEING 737':inside?'CREW REST':'FREE ROAM'}</span><h2>{seat?'Take the captain’s seat.':exit?'Forward left door.':cabin?'Make your way through the cabin.':near?'Welcome aboard.':inside?'Take a break.':'Explore the airport.'}</h2><p>{seat?'Press E to sit down and use the flight controls.':exit?'Press E to step outside, or follow the aisle to explore.':cabin?'Walk along the aisle. The cockpit is at the front, beyond the forward entry.':near?'Enter through the forward door and explore the cabin before taking your seat.':inside?'Rest here and choose when to continue your day.':`Pilot lounge: ${Math.round(Math.hypot(p.x-lounge.x,p.z-lounge.z))} m. Return to the forward left door to enter your aircraft.`}</p>
 {action?<button className="primary" onClick={onBoard}><Plane size={16}/>{action}<kbd>E</kbd></button>:inside?<div className={styles.rest}><button onClick={()=>onRest(false)}><Sun size={15}/> Rest until morning</button><button onClick={()=>onRest(true)}><Moon size={15}/> Rest until night</button></div>:null}</aside>
 <div className={styles.controls}><span><kbd>W A S D</kbd> Walk</span><span><kbd>Shift</kbd> Run outside</span><span>Drag to look · Arrows to turn</span><button onClick={onView}><Camera size={14}/> {p.view}<kbd>C</kbd></button><button onClick={onPause}>{s.paused?'Resume':'Pause'} <kbd>P</kbd></button></div>
 </div>
}
