'use client';
import styles from './PilotOverlay.module.css';
import {Footprints,Plane,Sun,Moon,MapPin,Compass} from 'lucide-react';
import {boardingPoint,canBoard,inLounge,loungePoint,type PilotState} from '@/lib/flight/pilot';
import type {FlightState} from '@/lib/flight/physics';
export function PilotOverlay({p,s,onBoard,onRest,onPause}:{p:PilotState;s:FlightState;onBoard:()=>void;onRest:(night:boolean)=>void;onPause:()=>void}){
 const door=boardingPoint(s),lounge=loungePoint(p),near=canBoard(p,s),inside=inLounge(p),distance=Math.hypot(p.x-door.x,p.z-door.z);
 const sx=(x:number)=>150+(x-p.x)*.65,sz=(z:number)=>120+(z-p.z)*.65;
 return <div className={styles.overlay}>
 <div className={styles.title}><span className="eyebrow"><Footprints size={14}/> PILOT LIFE · {p.airport===0?'SEATTLE':'EVERETT'}</span><h1>{inside?'A moment between flights.':'Your day beyond the cockpit.'}</h1><p>{inside?'Pilot lounge': 'On foot'} · {Math.floor(s.time).toString().padStart(2,'0')}:{Math.floor(s.time%1*60).toString().padStart(2,'0')} local</p></div>
 <aside className={styles.map+' panel'}><div className="panel-heading"><Compass size={14}/> AIRPORT & SURROUNDINGS <span>N ↑</span></div><svg width="300" height="240" style={{width:'100%',height:'auto'}} viewBox="0 0 300 240" aria-label="Local walking map with your position, aircraft and pilot lounge"><rect width="300" height="240" fill="#385b4c"/><rect x={sx(-30)} y={sz(p.airport-1500)} width="39" height="1950" fill="#52636a"/><path d={`M ${sx(50)} ${sz(p.airport+1110)} H ${sx(102)}`} stroke="#a3ac94" strokeWidth="5"/><rect x={sx(78)} y={sz(p.airport+1092)} width="16" height="11" fill="#e9c995"/><text x={sx(90)+12} y={sz(lounge.z)} fill="#fff" fontSize="10">LOUNGE</text><g transform={`translate(${sx(s.x)} ${sz(s.z)}) rotate(${s.heading*180/Math.PI})`}><path d="M 0 -10 L 3 -1 L 10 4 L 2 3 L 2 8 L -2 8 L -2 3 L -10 4 L -3 -1 Z" fill="#f4b264"/></g><circle cx="150" cy="120" r="6" fill="#bcffe0"/><path d="M 0 -16 L -5 -7 L 5 -7 Z" fill="#bcffe0" transform={`translate(150 120) rotate(${p.heading*180/Math.PI})`}/></svg><div className={styles.distance}><span><Plane size={13}/> Aircraft {Math.round(distance)} m</span><span>{(p.walked/1000).toFixed(2)} km walked</span></div></aside>
 <div className={styles.crosshair} aria-hidden="true">·</div>
 <aside className={styles.action+' panel'}><span className="eyebrow"><MapPin size={13}/> {near?'YOUR BOEING 737':inside?'CREW REST':'FREE ROAM'}</span><h2>{near?'Ready for your next chapter?':inside?'Take a break.':'Go wherever the day takes you.'}</h2><p>{near?'Board at the forward left door and return to the flight deck.':inside?'Rest here and choose when to continue your day.':`Explore the airport, watch passing crew, or take the causeway toward the city. Pilot lounge: ${Math.round(Math.hypot(p.x-lounge.x,p.z-lounge.z))} m.`}</p>{near?<button className="primary" onClick={onBoard}><Plane size={16}/> Board aircraft <kbd>E</kbd></button>:inside?<div className={styles.rest}><button onClick={()=>onRest(false)}><Sun size={15}/> Rest until morning</button><button onClick={()=>onRest(true)}><Moon size={15}/> Rest until night</button></div>:<p className="pilot-bearing">Aircraft bearing {((Math.atan2(door.x-p.x,-(door.z-p.z))*180/Math.PI+360)%360).toFixed(0)}°</p>}</aside>
 <div className={styles.controls}><span><kbd>W A S D</kbd> Walk</span><span><kbd>Shift</kbd> Run</span><span>Drag to look · Arrow keys to turn</span><span><kbd>E</kbd> Board nearby</span><button onClick={onPause}>{s.paused?'Resume':'Pause'} <kbd>P</kbd></button></div>
 </div>
}
