import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
export type TreePosition={x:number;y:number;z:number;height:number;rotation:number};
export class DetailedForest {
 private leafAlpha:THREE.Texture|null=null;private atlas:THREE.WebGLRenderTarget|null=null;private cards:THREE.InstancedMesh|null=null;private detail:THREE.InstancedMesh[]=[];private disposed=false;private lastX=Infinity;private lastZ=Infinity;private lastQuality='';private cardMatrices:THREE.Matrix4[]=[];private maxDetail=24;
 constructor(private scene:THREE.Scene,private positions:TreePosition[],renderer:THREE.WebGLRenderer,manager:THREE.LoadingManager){Promise.all([new THREE.TextureLoader(manager).loadAsync('/assets/hd/tree/textures/island_tree_01_leaves_alpha_1k.png'),new GLTFLoader(manager).loadAsync('/assets/hd/tree/tree-optimized.gltf')]).then(([leafAlpha,gltf])=>{this.leafAlpha=leafAlpha;leafAlpha.anisotropy=8;if(this.disposed){leafAlpha.dispose();gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();}});return;}gltf.scene.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(gltf.scene),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),scale=20/size.y;
 const normalization=new THREE.Matrix4().makeScale(scale,scale,scale).multiply(new THREE.Matrix4().makeTranslation(-center.x,-bounds.min.y,-center.z));const bake=new THREE.Scene();bake.environment=scene.environment;bake.environmentIntensity=.4;const key=new THREE.DirectionalLight(0xfff3df,2.5);key.position.set(-10,25,15);bake.add(key,new THREE.HemisphereLight(0xcce9ff,0x626e3b,1.5));
 const tree=new THREE.Group();bake.add(tree);
 gltf.scene.traverse(o=>{if(!(o instanceof THREE.Mesh))return;const geo=o.geometry.clone();geo.applyMatrix4(new THREE.Matrix4().multiplyMatrices(normalization,o.matrixWorld));const mats=(Array.isArray(o.material)?o.material:[o.material]).map(m=>{const mat=m.clone() as THREE.MeshStandardMaterial;if(mat.name.includes('leaves')){mat.alphaMap=leafAlpha;mat.alphaTest=.45;mat.transparent=false;mat.depthWrite=true;}mat.side=THREE.DoubleSide;mat.roughness=.86;mat.envMapIntensity=.6;for(const key of ['map','normalMap','roughnessMap'] as const){if(mat[key])mat[key]!.anisotropy=8;}return mat;});const mat=Array.isArray(o.material)?mats:mats[0];const mesh=new THREE.Mesh(geo,mat);tree.add(mesh);const instanced=new THREE.InstancedMesh(geo,mat,this.maxDetail);instanced.count=0;instanced.castShadow=true;instanced.receiveShadow=true;instanced.frustumCulled=false;this.detail.push(instanced);scene.add(instanced);o.geometry.dispose();});
 this.atlas=new THREE.WebGLRenderTarget(2048,2048,{minFilter:THREE.LinearMipmapLinearFilter,magFilter:THREE.LinearFilter,generateMipmaps:true});const savedTarget=renderer.getRenderTarget(),color=renderer.getClearColor(new THREE.Color()),alpha=renderer.getClearAlpha(),tone=renderer.toneMapping,autoClear=renderer.autoClear;const viewport=renderer.getViewport(new THREE.Vector4()),scissor=renderer.getScissor(new THREE.Vector4()),scissorTest=renderer.getScissorTest();renderer.setRenderTarget(this.atlas);renderer.setClearColor(0,0);renderer.setScissorTest(false);renderer.clear();renderer.toneMapping=THREE.NoToneMapping;renderer.autoClear=false;const cam=new THREE.OrthographicCamera(-13,13,23,-3,.1,100);
 for(let i=0;i<4;i++){cam.position.set(Math.sin(i*Math.PI/2)*40,10,Math.cos(i*Math.PI/2)*40);cam.lookAt(0,10,0);renderer.setViewport((i%2)*1024,Math.floor(i/2)*1024,1024,1024);renderer.setScissor((i%2)*1024,Math.floor(i/2)*1024,1024,1024);renderer.setScissorTest(true);renderer.render(bake,cam);}
 renderer.setRenderTarget(savedTarget);renderer.setViewport(viewport);renderer.setScissor(scissor);renderer.setScissorTest(scissorTest);renderer.setClearColor(color,alpha);renderer.toneMapping=tone;renderer.autoClear=autoClear;
 const card=new THREE.PlaneGeometry(26,26);card.translate(0,10,0);const variants=new Float32Array(positions.length);for(let i=0;i<variants.length;i++)variants[i]=i%4;card.setAttribute('treeVariant',new THREE.InstancedBufferAttribute(variants,1));const cardMat=new THREE.MeshBasicMaterial({map:this.atlas.texture,alphaTest:.38,side:THREE.DoubleSide,fog:true});
 cardMat.onBeforeCompile=shader=>{shader.vertexShader='attribute float treeVariant;varying float vTreeVariant;\n'+shader.vertexShader;shader.fragmentShader='varying float vTreeVariant;\n'+shader.fragmentShader;shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>',`vTreeVariant=treeVariant;vec3 base=(modelMatrix*instanceMatrix*vec4(0.,0.,0.,1.)).xyz;float treeScale=length(instanceMatrix[0].xyz);vec3 right=normalize(vec3(viewMatrix[0][0],0.,viewMatrix[2][0]));vec3 worldBillboard=base+right*position.x*treeScale+vec3(0.,position.y*treeScale,0.);vec4 mvPosition=viewMatrix*vec4(worldBillboard,1.);gl_Position=projectionMatrix*mvPosition;`);shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>',`vec2 atlasUV=(vMapUv+vec2(mod(vTreeVariant,2.),floor(vTreeVariant/2.)))*.5;diffuseColor*=texture2D(map,atlasUV);`);};
 this.cards=new THREE.InstancedMesh(card,cardMat,positions.length);this.cards.frustumCulled=false;const obj=new THREE.Object3D();positions.forEach((p,i)=>{obj.position.set(p.x,p.y,p.z);obj.scale.setScalar(p.height/20);obj.updateMatrix();this.cards!.setMatrixAt(i,obj.matrix);this.cardMatrices.push(obj.matrix.clone());this.cards!.setColorAt(i,new THREE.Color().setScalar(.86+(i%7)*.025));});scene.add(this.cards);this.update(new THREE.Vector3(0,25,1182),'Ultra');}).catch(()=>{});}
 update(eye:THREE.Vector3,quality:string){if(!this.cards||!this.detail.length)return;if(Math.hypot(eye.x-this.lastX,eye.z-this.lastZ)<60&&quality===this.lastQuality)return;this.lastX=eye.x;this.lastZ=eye.z;this.lastQuality=quality;const near=this.positions.map((p,i)=>({p,i,d:Math.hypot(eye.x-p.x,eye.z-p.z)})).filter(t=>t.d<(quality==='Ultra'?650:quality==='High'?400:0)).sort((a,b)=>a.d-b.d).slice(0,quality==='Ultra'?24:12);const ids=new Set(near.map(t=>t.i));const hidden=new THREE.Matrix4().makeScale(0,0,0);this.positions.forEach((_,i)=>this.cards!.setMatrixAt(i,ids.has(i)?hidden:this.cardMatrices[i]));this.cards.instanceMatrix.needsUpdate=true;
 const obj=new THREE.Object3D();this.detail.forEach(mesh=>{mesh.count=near.length;near.forEach(({p},i)=>{obj.position.set(p.x,p.y,p.z);obj.rotation.set(0,p.rotation,0);obj.scale.setScalar(p.height/20);obj.updateMatrix();mesh.setMatrixAt(i,obj.matrix);});mesh.instanceMatrix.needsUpdate=true;});}
 setNight(night:number){if(this.cards)(this.cards.material as THREE.MeshBasicMaterial).color.setScalar(1-night*.94);}
 dispose(){this.disposed=true;this.atlas?.dispose();this.leafAlpha?.dispose();}
}
