import * as THREE from 'three';
import { Sky } from 'three/addons/objects/Sky.js';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { SSAOPass } from 'three/addons/postprocessing/SSAOPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import type { FlightState } from './physics';
export type CameraMode='Chase'|'Cockpit'|'Free';
function material(color:number,roughness=.65,metalness=.05){return new THREE.MeshStandardMaterial({color,roughness,metalness});}
function box(parent:THREE.Object3D,w:number,h:number,d:number,x:number,y:number,z:number,mat:THREE.Material){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function wing(parent:THREE.Object3D,points:number[][],mat:THREE.Material){const shape=new THREE.Shape();points.forEach((p,i)=>i?shape.lineTo(p[0],p[1]):shape.moveTo(p[0],p[1]));shape.closePath();const g=new THREE.ExtrudeGeometry(shape,{depth:.18,bevelEnabled:false});g.rotateX(Math.PI/2);const m=new THREE.Mesh(g,mat);m.castShadow=true;parent.add(m);return m;}
function createAircraft(){const group=new THREE.Group(),white=material(0xe9eeed,.36,.22),navy=material(0x12364b,.4,.22),dark=material(0x101c27,.2,.6),metal=material(0x88969d,.3,.8);const points=[new THREE.Vector2(.05,-19.8),new THREE.Vector2(.6,-18.5),new THREE.Vector2(1.5,-15),new THREE.Vector2(1.85,-11),new THREE.Vector2(1.86,9),new THREE.Vector2(1.4,14),new THREE.Vector2(.65,18),new THREE.Vector2(.08,20)];const fus=new THREE.Mesh(new THREE.LatheGeometry(points,32),white);fus.rotation.x=-Math.PI/2;fus.castShadow=true;group.add(fus);
 // Forward end is local -Z.
 for(const side of [-1,1]){wing(group,[[side*1.2,-5],[side*17,3.5],[side*17,5.2],[side*4,3.5],[side*1.2,5]],white);const tip=box(group,.17,2.5,1.6,side*17,1.1,4.3,navy);tip.rotation.z=side*-.2;wing(group,[[side*.8,12],[side*6.5,16.7],[side*6.5,18],[side*.8,16]],white);const eng=new THREE.Mesh(new THREE.CylinderGeometry(1.15,1.0,4.9,24),white);eng.rotation.x=Math.PI/2;eng.position.set(side*5,-1.2,-2);eng.castShadow=true;group.add(eng);const intake=new THREE.Mesh(new THREE.CylinderGeometry(.92,.92,.08,24),dark);intake.rotation.x=Math.PI/2;intake.position.set(side*5,-1.2,-4.49);group.add(intake);const hub=new THREE.Mesh(new THREE.ConeGeometry(.29,.8,16),metal);hub.rotation.x=-Math.PI/2;hub.position.set(side*5,-1.2,-4.4);group.add(hub);
  for(let i=0;i<28;i++){const window=box(group,.04,.30,.40,side*1.84,.52,-10+i*.72,dark);window.rotation.z=side*.15;}
  const stripe=box(group,.035,.32,25,side*1.83,-.15,0,navy);stripe.rotation.z=side*-.05;
  const light=new THREE.Mesh(new THREE.SphereGeometry(.13,8,6),new THREE.MeshBasicMaterial({color:side<0?0xff3344:0x45ffb5}));light.position.set(side*17,1.2,4);group.add(light);
 }
 const fin=wing(group,[[0,10],[5.8,16.8],[5.8,18.8],[0,17.7]],navy);fin.rotation.z=Math.PI/2;fin.position.y=.8;
 const cockpit=box(group,2.3,.65,1.8,0,.95,-14.5,dark);cockpit.rotation.x=.2;
 const gear=new THREE.Group();const noseGear=new THREE.Group();for(const [x,z] of [[-2.5,3],[2.5,3],[0,-12]]){const target=z<0?noseGear:gear;box(target,.17,1.6,.2,x,-2,z,metal);for(const side of [-1,1]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(z<0?.36:.55,z<0?.36:.55,.3,14),dark);wheel.rotation.z=Math.PI/2;wheel.position.set(x+side*.3,-2.65,z);target.add(wheel);}}group.add(gear,noseGear);
 return {group,gear,noseGear};}
export class FlightRenderer{
 renderer:THREE.WebGLRenderer;scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(56,1,.2,100000);plane=createAircraft();sun=new THREE.DirectionalLight(0xffe4be,3);ambient=new THREE.HemisphereLight(0xc3def4,0x526144,2.2);sky=new Sky();composer:EffectComposer;ao:SSAOPass;bloom:UnrealBloomPass;rain:THREE.Points;clouds=new THREE.Group();mode:CameraMode='Chase';quality=true;freeAngle=.65;freeHeight=24;zoom=82;disposed=false;resizeObserver:ResizeObserver;lastWeather='';lights:THREE.Mesh[]=[];target=new THREE.Vector3();desired=new THREE.Vector3();
 constructor(private container:HTMLElement){this.renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.7;container.appendChild(this.renderer.domElement);this.scene.fog=new THREE.FogExp2(0xb6c8d1,.000028);this.sky.scale.setScalar(80000);this.scene.add(this.sky);const u=this.sky.material.uniforms;u.turbidity.value=4;u.rayleigh.value=1.8;u.mieCoefficient.value=.006;u.mieDirectionalG.value=.8;this.scene.add(this.ambient,this.sun);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-130,right:130,top:130,bottom:-130,near:10,far:1200});this.sun.shadow.bias=-.0003;this.scene.add(this.sun.target);
 this.buildWorld();this.scene.add(this.plane.group);this.camera.position.set(48,25,1180);
 const raingeo=new THREE.BufferGeometry(),rainpos=new Float32Array(2400);for(let i=0;i<rainpos.length;i+=3){rainpos[i]=(Math.random()-.5)*180;rainpos[i+1]=Math.random()*100;rainpos[i+2]=(Math.random()-.5)*180;}raingeo.setAttribute('position',new THREE.BufferAttribute(rainpos,3));this.rain=new THREE.Points(raingeo,new THREE.PointsMaterial({color:0xc4d9e2,size:.16,transparent:true,opacity:.55}));this.scene.add(this.rain);
 this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.ao=new SSAOPass(this.scene,this.camera,800,600);this.ao.kernelRadius=8;this.ao.minDistance=.002;this.ao.maxDistance=.06;this.composer.addPass(this.ao);this.ao.enabled=false;this.bloom=new UnrealBloomPass(new THREE.Vector2(800,600),.16,.3,.88);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(container);this.resize();container.addEventListener('pointerdown',this.pointerDown);container.addEventListener('wheel',this.wheel,{passive:false});}
 buildWorld(){const grass=material(0x566d49),tarmac=material(0x3b4344,.94),concrete=material(0x92968d,.88),paint=material(0xe2e4d7,.8),yellow=material(0xd5b557);
 const ocean=new THREE.Mesh(new THREE.PlaneGeometry(120000,120000),new THREE.MeshStandardMaterial({color:0x537f90,roughness:.29,metalness:.4}));ocean.rotation.x=-Math.PI/2;ocean.position.y=-8;this.scene.add(ocean);
 box(this.scene,18000,12,62000,7200,-6,-12000,grass);box(this.scene,6000,9,60000,-14000,-8,-12000,material(0x3f614b));
 // Airfields share a training elevation and are intentionally compressed.
 for(const z of [0,-25000]){box(this.scene,750,.10,3500,0,.04,z,material(0x6c7b52));box(this.scene,60,.12,3000,0,.15,z,tarmac);box(this.scene,19,.12,3000,135,.12,z,tarmac);box(this.scene,320,.11,900,285,.10,z+300,concrete);
 for(const dz of [-1200,-500,200,900])box(this.scene,135,.14,22,67,.16,z+dz,tarmac);
 for(const x of [-28,28])box(this.scene,.55,.02,2970,x,.23,z,paint);
 for(let dz=-1450;dz<1500;dz+=100){box(this.scene,1,.02,40,0,.24,z+dz,paint);for(const x of [-33,33]){const light=new THREE.Mesh(new THREE.SphereGeometry(.4,5,4),new THREE.MeshBasicMaterial({color:0xffe6ac}));light.position.set(x,.65,z+dz);this.scene.add(light);this.lights.push(light);}}
 for(const end of [-1,1]){for(const side of [-1,1])for(let i=0;i<6;i++)box(this.scene,2.8,.03,38,side*(6+i*3.4),.26,z+end*1420,paint);box(this.scene,5,.03,40,-15,.26,z+end*1050,paint);box(this.scene,5,.03,40,15,.26,z+end*1050,paint);}
 const cv=document.createElement('canvas');cv.width=256;cv.height=256;const cx=cv.getContext('2d')!;cx.fillStyle='#e2e4d7';cx.font='bold 145px Arial';cx.textAlign='center';cx.fillText('36',128,180);const tex=new THREE.CanvasTexture(cv);const number=new THREE.Mesh(new THREE.PlaneGeometry(26,30),new THREE.MeshBasicMaterial({map:tex,transparent:true}));number.rotation.x=-Math.PI/2;number.position.set(0,.28,z+1330);this.scene.add(number);
 box(this.scene,.25,.03,2900,135,.24,z,yellow);
 for(let i=0;i<5;i++){box(this.scene,70,16,80,290,8,z-500+i*155,material(0xb7bcba));box(this.scene,73,2,83,290,16.5,z-500+i*155,material(0x5f717c));box(this.scene,4,4,85,253,5,z-500+i*155,material(0x506a78));}
 box(this.scene,14,43,14,200,21.5,z+1000,material(0xabb6b5));box(this.scene,24,8,24,200,46,z+1000,material(0x385768,.27,.4));
 }
 // Repeated buildings and trees use instancing to keep draw calls bounded.
 let seed=137;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};
 const city=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),material(0x9eadae),650);const dummy=new THREE.Object3D();for(let i=0;i<650;i++){let x=650+rand()*8000,z=5500-rand()*42000;const h=10+Math.pow(rand(),3)*200;dummy.position.set(x,h/2,z);dummy.scale.set(30+rand()*65,h,30+rand()*65);dummy.updateMatrix();city.setMatrixAt(i,dummy.matrix);city.setColorAt(i,new THREE.Color().setHSL(.54,.08,.35+rand()*.3));}city.castShadow=true;city.receiveShadow=true;this.scene.add(city);
 const trees=new THREE.InstancedMesh(new THREE.ConeGeometry(1,1,5),material(0x304d37),1800);for(let i=0;i<1800;i++){const x=rand()*14000-1800,z=5000-rand()*40000;if(Math.abs(x)<430&&(Math.abs(z)<2000||Math.abs(z+25000)<2000)){dummy.scale.set(0,0,0);}else{const h=8+rand()*18;dummy.scale.set(h*.28,h,h*.28);}dummy.position.set(x,dummy.scale.y/2,z);dummy.updateMatrix();trees.setMatrixAt(i,dummy.matrix);}this.scene.add(trees);
 for(let i=0;i<38;i++){const h=900+rand()*2600;const lod=new THREE.LOD();for(const [segments,dist] of [[10,0],[5,16000]]){const mountain=new THREE.Mesh(new THREE.ConeGeometry(1800+rand()*1900,h,segments),material(i%3===0?0x9fadb1:0x697e7e));lod.addLevel(mountain,dist);}lod.position.set(i<20?13000+rand()*8000:-18000-rand()*5000,h/2-30,8000-rand()*65000);this.scene.add(lod);}
 const cloudMat=new THREE.MeshStandardMaterial({color:0xe7ecea,roughness:1,transparent:true,opacity:.75,depthWrite:false});for(let i=0;i<45;i++){const cloud=new THREE.Mesh(new THREE.IcosahedronGeometry(1,1),cloudMat);cloud.position.set((rand()-.5)*30000,1500+rand()*1200,5000-rand()*43000);cloud.scale.set(350+rand()*700,100+rand()*120,220+rand()*500);this.clouds.add(cloud);}this.scene.add(this.clouds);
 }
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;if(!w||!h)return;this.renderer.setSize(w,h);this.composer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 pointerDown=(e:PointerEvent)=>{if(this.mode!=='Free')return;const startX=e.clientX,startY=e.clientY,angle=this.freeAngle,height=this.freeHeight;const move=(ev:PointerEvent)=>{this.freeAngle=angle+(ev.clientX-startX)*.007;this.freeHeight=Math.max(3,Math.min(160,height+(ev.clientY-startY)*.3));};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);};
 wheel=(e:WheelEvent)=>{if(this.mode!=='Free')return;e.preventDefault();this.zoom=Math.max(25,Math.min(300,this.zoom+e.deltaY*.05));};
 render(s:FlightState,dt:number){const p=this.plane.group;p.position.set(s.x,s.y,s.z);p.rotation.set(s.pitch,-s.heading,-s.bank,'YXZ');this.plane.gear.scale.y=Math.max(.01,s.gearPosition);this.plane.noseGear.scale.y=Math.max(.01,s.gearPosition);this.plane.gear.visible=this.plane.noseGear.visible=s.gearPosition>.05;
 const chase=this.mode==='Chase';if(this.mode==='Cockpit'){this.desired.set(0,1.35,-13);this.desired.applyQuaternion(p.quaternion).add(p.position);this.target.set(0,1.3,-500).applyQuaternion(p.quaternion).add(p.position);this.camera.position.copy(this.desired);this.camera.up.set(0,1,0).applyQuaternion(p.quaternion);}else{const angle=chase?.25:this.freeAngle;this.desired.set(Math.sin(angle)*this.zoom,chase?23:this.freeHeight,Math.cos(angle)*this.zoom);this.desired.applyAxisAngle(new THREE.Vector3(0,1,0),-s.heading).add(p.position);this.camera.position.lerp(this.desired,1-Math.exp(-dt*3));this.target.copy(p.position).add(new THREE.Vector3(0,3,0));this.camera.up.set(0,1,0);}this.camera.lookAt(this.target);
 const elevation=Math.sin((s.time-6)/12*Math.PI);const sunvec=new THREE.Vector3(-.6,Math.max(-.2,elevation),-.7).normalize();this.sky.material.uniforms.sunPosition.value.copy(sunvec);const daylight=Math.max(.04,elevation);this.sun.intensity=daylight*3;this.ambient.intensity=.2+daylight*1.6;this.sun.position.copy(p.position).addScaledVector(sunvec,500);this.sun.target.position.copy(p.position);this.renderer.toneMappingExposure=.55+daylight*.24;
 const fog=this.scene.fog as THREE.FogExp2;fog.density=s.weather==='Fog'?.00065:s.weather==='Rain'?.00016:s.weather==='Cloudy'?.000055:.000028;fog.color.setHSL(.56,.15,.12+daylight*.6);this.clouds.visible=s.weather!=='Clear';this.rain.visible=s.weather==='Rain';if(this.rain.visible){this.rain.position.copy(p.position);const attr=this.rain.geometry.attributes.position;for(let i=0;i<attr.count;i++){let y=attr.getY(i)-dt*55;if(y<0)y=100;attr.setY(i,y);}attr.needsUpdate=true;}
 this.bloom.strength=elevation<.1?.35:.12;this.ao.enabled=this.quality&&this.mode!=='Cockpit';if(this.quality)this.composer.render(dt);else this.renderer.render(this.scene,this.camera);
 }
 dispose(){this.disposed=true;this.resizeObserver.disconnect();this.container.removeEventListener('pointerdown',this.pointerDown);this.container.removeEventListener('wheel',this.wheel);this.scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Points){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if('map'in m)(m.map as THREE.Texture)?.dispose();m.dispose();});}});this.composer.passes.forEach(p=>p.dispose());this.composer.dispose();this.renderer.dispose();this.renderer.domElement.remove();}
}
